<div class="mobile-bottom-navbar" data-app="mobile-navbar">
	<div class="mobile-bottom-navbar-inner">
		<button class="navbar-ctrl" data-an="show-lsb">
			<?php echo cl_ikon('ellypsis-vertical'); ?>
		</button>
		<button class="navbar-ctrl" data-anchor="<?php echo cl_link('notifications'); ?>">
			<?php echo cl_ikon('bell'); ?>
			<span class="info-indicators" data-an="new-notifs"><?php echo fetch_or_get($me['new_notifs']); ?></span>
		</button>
		<button class="navbar-ctrl" data-toggle="modal" data-target="#add_new_post">
			<?php echo cl_ikon('add'); ?>
		</button>
		<button class="navbar-ctrl" data-anchor="<?php echo cl_link("chats"); ?>">
			<?php echo cl_ikon('chat-alt'); ?>
			<span class="info-indicators" data-an="new-messages"><?php echo fetch_or_get($me['new_messages']); ?></span>
		</button>
		<button class="navbar-ctrl" data-anchor="<?php echo cl_link("search"); ?>">
			<?php echo cl_ikon('search'); ?>
		</button>
	</div>
</div>

<script>
	$(document).ready(function($) {
		var _app = $('[data-app="mobile-navbar"]');

		_app.find('[data-an="show-lsb"]').on('click', function(event) {
			event.preventDefault();
			
			$('div[data-app="left-sidebar"]').addClass('show').promise().done(function() {;
				$('body').addClass('ov-h').append($('<div>', {
					'class': 'sb-open-overlay',
					'data-app': 'lsb-back-drop',

				}));
			});		
		});

		$(document).on('click', 'div[data-app="lsb-back-drop"]', function(event) {
			event.preventDefault();
			var _self = $(this);

			$('div[data-app="left-sidebar"]').removeClass('show').promise().done(function() {
				_self.remove();
				$('body').removeClass('ov-h');
			});
		});
	});
</script>