<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>
		<?php if (not_empty($me['new_notifs'])): ?>
			(<?php echo fetch_or_get($me['new_notifs']); ?>)
		<?php endif; ?>
		
		<?php echo fetch_or_get($cl["page_title"],$cl["config"]["title"]); ?>
	</title>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="title" content="<?php echo fetch_or_get($cl["page_title"], $cl["config"]["title"]); ?>"/>
    <meta name="description" content="<?php echo fetch_or_get($cl["page_desc"], $cl["config"]["description"]); ?>"/>
    <meta name="keywords" content="<?php echo fetch_or_get($cl['page_kw'], $cl["config"]["keywords"]);?>"/>
    <meta name="image" content="<?php echo fetch_or_get($cl['page_img'], $cl["config"]["site_logo"]);?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	
	<?php if ($cl["pn"] == 'thread'): ?>
		<meta property="og:type" content="article" />
		<meta property="og:image" content="<?php echo fetch_or_get($cl["page_image"], ''); ?>"/>
		<meta property="og:image:secure_url" content="<?php echo fetch_or_get($cl["page_image"], ''); ?>" />
		<meta property="og:description" content="<?php echo fetch_or_get($cl["page_desc"], $cl["config"]["description"]); ?>" />
		<meta property="og:title" content="<?php echo fetch_or_get($cl["page_title"], $cl["config"]["title"]); ?>" />
		<meta property="og:url" content="<?php echo fetch_or_get($cl["page_url"], $cl["config"]["url"]); ?>" />
		<meta name="twitter:card" content="summary">
		<meta name="twitter:title" content="<?php echo fetch_or_get($cl["page_title"], $cl["config"]["title"]); ?>" />
		<meta name="twitter:description" content="<?php echo fetch_or_get($cl["page_desc"], $cl["config"]["description"]); ?>" />
		<meta name="twitter:image" content="<?php echo fetch_or_get($cl["page_image"], ''); ?>" />
	<?php endif; ?>

	<?php if (in_array($cl["pn"], array("profile", "connections"))): ?>
		<?php if ($cl['prof_user']['index_privacy'] == 'N'): ?>
		    <meta name="robots" content="noindex">
		    <meta name="googlebot" content="noindex">
	    <?php endif; ?>
    <?php endif; ?>

	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/bootstrap-v4.0.0.min.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/animate.min.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/materialize.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/preloader.min.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/material_icon_fonts/material_icon.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/apps/common/style.master.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/apps/common/style.mq.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/apps/common/style.custom.css?v={%config version%}">
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/waitMe.min.css?v={%config version%}">

	<?php if ($cl["theme_mode"] == "N"): ?>
		<link rel="stylesheet" href="{%config theme_url%}/statics/css/apps/common/style.dark.css?v={%config version%}">
	<?php endif; ?>
	<link rel="stylesheet" href="{%config theme_url%}/statics/css/libs/jquery.fancybox.css?v={%config version%}">
	<link rel="icon" href="{%config site_fav%}" type="image/png">

	<script src="{%config theme_url%}/statics/js/libs/jquery-3.5.1.min.js?v={%config version%}"></script>
	<?php if ($cl["server_mode"] == 'development'): ?>
		<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-v2.6.11.dev.min.js?v={%config version%}"></script>
	<?php else: ?>
		<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-v2.6.11.min.js?v={%config version%}"></script>
	<?php endif; ?>
	
	<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-plugins/validators.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/vuejs/vue-plugins/vuelidate.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/jquery-plugins/jquery.form-v4.2.2.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/popper.1.12.9.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/bootstrap.v4.0.0.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/afterglow/afterglow.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/sticky-sidebar/source/jquery.sticky-sidebar.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/master.script.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/custom.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/clipboard.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/jquery-plugins/jquery.fancybox.min.js?v={%config version%}"></script>
	<script src="{%config theme_url%}/statics/js/libs/lozad.min.js"></script>
	<script src="{%config theme_url%}/statics/js/libs/waitme/waitMe.min.js"></script>
	<script src="{%config theme_url%}/statics/js/libs/txt.autoresize.min.js"></script>
	<script src="{%config theme_url%}/statics/js/libs/audio-recorder.js"></script>
</head>
<body class="cl-app-<?php echo fetch_or_get($cl["pn"], "none"); ?>">
	<div class="main-preloader-holder" id="main-preloader-holder">
		<div class="main-preloader">
			<div class="loading">
				<div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
			</div>
		</div>
	</div>
	<div data-el="main-content-holder">
		<main class="main-content-container <?php echo (($cl["is_logged"]) ? "" : "guest-mode" ); ?>">
			<div class="main-content-container-inner">
				<?php if (not_empty($cl["sbl"])): ?>
					<?php if (not_empty($cl["is_logged"])): ?>
						<?php echo cl_template('main/left_sidebar'); ?>
					<?php else: ?>
						<?php echo cl_template('main/left_sidebar_guest'); ?>
					<?php endif; ?>
				<?php endif; ?>

				<div data-el="timeline-container-wrapper" class="timeline-container-wrapper">
					<div data-el="timeline-content" class="timeline-container-inner">
						<?php echo $cl["http_res"]; ?>
					</div>

					<div data-el="spa-preloader" class="spa-preloader d-none">
						<div class="spa-preloader-inner">
							<span class="spinner-icon">
								<?php echo cl_ikon("spinner-icon"); ?>
							</span>
						</div>
					</div>
				</div>

				<?php if (not_empty($cl["sbr"])): ?>
					<?php echo cl_template('main/right_sidebar'); ?>
				<?php endif; ?>
			</div>
		</main>

		<?php if (not_empty($cl["is_logged"]) && in_array($cl["pn"], array("conversation")) != true): ?>
			<?php echo cl_template('main/bottom_navbar'); ?>
		<?php endif; ?>

		<input id="csrf-token" type="hidden" class="hidden d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>">

		<?php if ($cl['is_logged']): ?>
			<div class="modal fade vh-center modal-pubbox" data-app="modal-pubbox" id="add_new_post" tabindex="-1" role="dialog" aria-hidden="true">
			    <div class="modal-dialog" role="document">
			        <div class="modal-content">
			            <div class="modal-header">
			                <div class="main---mh--block">
			                    <h5 class="modal-title" data-an="modal-title">
			                    	<?php echo cl_translate('New post'); ?>
			                   	</h5>
			                    <span class="dismiss-modal" data-dismiss="modal">
			                        <?php echo cl_ikon('close'); ?>
			                    </span>
			                </div>
			            </div>
			            <div class="modal-body">
			                <?php $cl['pb_id'] = 2; echo cl_template('timeline/pubbox'); ?>
			            </div>
			        </div>
			    </div>
			</div>
			<?php echo cl_template('timeline/scripts/pubbox_master_script'); ?>	
		<?php endif; ?>
		<div data-app="black-hole"></div>
		<?php if (not_empty($cl['config']['google_analytics'])): ?>
			<?php echo htmlspecialchars_decode($cl['config']['google_analytics']); ?>
		<?php endif; ?>

		<?php if ($cl["pn"] != 'guest'): ?>
			<?php echo cl_template("main/scripts/app_master_script"); ?>
		<?php endif; ?>

		<?php if ($cl['is_logged']): ?>
			<?php if (in_array($cl["pn"], array("bookmarks", "home", "profile", "search", "thread"))): ?>
				<?php echo cl_template("main/modals/report_post"); ?>
			<?php endif; ?>
		<?php endif; ?>
	</div>
	<div class="announcement-holder" data-app="announcement"></div>

	<?php if (empty($_COOKIE['__c_u_a__'])): ?>
		<?php if ($cl["pn"] != "stat_pages"): ?>
			<?php echo cl_template("main/modals/cookies_alert"); ?>
		<?php endif; ?>
	<?php endif; ?>
</body>
</html>

