<div class="left-sb-container sidebar" data-app="left-sidebar">
	<div class="sidebar__inner">
		<div class="user-info">
			<div class="avatar">
				<img src="<?php echo($me['avatar']); ?>" alt="Avatar">
			</div>
			<div class="uname">
				<a href="<?php echo($me['url']); ?>" data-spa="true">
					<h5>
						<span class="user-name-holder <?php if ($me['verified'] == '1') {echo('verified-badge');} ?>">
							<?php echo($me['name']); ?>
						</span>
					</h5>
				</a>
			</div>
		</div>
		<div class="account-stats">
			<div class="stat-holder">
				<?php if (not_empty($me['following'])): ?>
					<a href="<?php echo(cl_strf('%s/following', $cl['me']['url'])); ?>" data-spa="true">
						<b data-an="total-following"><?php echo cl_number($me['following']); ?></b>
						<span><?php echo cl_translate('Following'); ?></span>
					</a>
				<?php else: ?>
					<b data-an="total-following"><?php echo cl_number($me['following']); ?></b>
					<span><?php echo cl_translate('Following'); ?></span>
				<?php endif; ?>
			</div>
			<div class="stat-holder">
				<?php if (not_empty($me['followers'])): ?>
					<a href="<?php echo(cl_strf('%s/followers', $cl['me']['url'])); ?>" data-spa="true">
						<b data-an="total-followers"><?php echo cl_number($me['followers']); ?></b>
						<span><?php echo cl_translate('Followers'); ?></span>
					</a>
				<?php else: ?>
					<b data-an="total-followers"><?php echo cl_number($me['followers']); ?></b>
					<span><?php echo cl_translate('Followers'); ?></span>
				<?php endif; ?>
			</div>
		</div>
		<div class="sidebar-v-nav-wrapper">
			<ul class="sidebar-v-nav">
				<li data-navitem="home" class="sidebar-v-nav-item <?php if($cl['pn'] == 'home') {echo('active');} ?>">
					<span class="icon">
						<?php echo cl_ikon('home'); ?>
					</span>
					<span class="nav-item-holder">
						<a href="<?php echo cl_link('/'); ?>" data-spa="true">
							<?php echo cl_translate('Home'); ?>
						</a>
					</span>
				</li>
				<li data-navitem="trending" class="sidebar-v-nav-item <?php if($cl['pn'] == 'trending') {echo('active');} ?>">
					<span class="icon">
						<?php echo cl_ikon('activity'); ?>
					</span>
					<span class="nav-item-holder">
						<a href="<?php echo cl_link('trending'); ?>" data-spa="true">
							<?php echo cl_translate('Trending'); ?>
						</a>
					</span>
				</li>
				<li data-navitem="search" class="sidebar-v-nav-item <?php if($cl['pn'] == 'search') {echo('active');} ?>">
					<span class="icon">
						<?php echo cl_ikon('hash'); ?>
					</span>
					<span class="nav-item-holder">
						<a href="<?php echo cl_link("search"); ?>" data-spa="true">
							<?php echo cl_translate('Explore'); ?>
						</a>
					</span>
				</li>
				<li class="sidebar-v-nav-item">
					<span class="icon">
						<?php echo cl_ikon('chevron-down'); ?>
					</span>
					<?php if (not_empty($me['new_notifs']) || not_empty($me['new_messages'])): ?>
						<span class="nav-item-holder dropdown group-ind-active" data-an="group-ind">
					<?php else: ?>
						<span class="nav-item-holder dropdown" data-an="group-ind">
					<?php endif; ?>
						<a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
							<?php echo cl_translate('More'); ?>
						</a>
						<div class="dropdown-menu dropdown-icons">
							<?php if (not_empty($cl['is_admin'])): ?>
								<a class="dropdown-item" href="<?php echo cl_link("admin_panel"); ?>">
									<span class="flex-item dropdown-item-icon">
										<?php echo cl_ikon('chart'); ?>
									</span>
									<span class="flex-item">
										<?php echo cl_translate('Control panel'); ?>
									</span>
								</a>
								<div class="dropdown-divider"></div>
							<?php endif; ?>
							<a class="dropdown-item" href="<?php echo cl_link("notifications"); ?>" data-spa="true">
								<span class="flex-item dropdown-item-icon">
									<?php echo cl_ikon('bell'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate('Notifications'); ?>
									<span class="info-indicators" data-an="new-notifs"><?php echo fetch_or_get($me['new_notifs']); ?></span>
								</span>
							</a>
							<a class="dropdown-item" href="<?php echo cl_link("chats"); ?>" data-spa="true">
								<span class="flex-item dropdown-item-icon">
									<?php echo cl_ikon('envelope'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate('Messages'); ?>
									<span class="info-indicators" data-an="new-messages"><?php echo fetch_or_get($me['new_messages']); ?></span>
								</span>
							</a>
							<a class="dropdown-item" href="<?php echo cl_link("bookmarks"); ?>" data-spa="true">
								<span class="flex-item dropdown-item-icon">
									<?php echo cl_ikon('bookmark'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate('Bookmarks'); ?>
								</span>
							</a>
							<a class="dropdown-item" href="<?php echo($me["url"]); ?>" data-spa="true">
								<span class="flex-item dropdown-item-icon">
									<?php echo cl_ikon('user'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate('Profile'); ?>
								</span>
							</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="<?php echo cl_link("wallet"); ?>" data-spa="true">
								<span class="flex-item dropdown-item-icon">
									<?php echo cl_ikon('credit-card'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate('Wallet'); ?> <b class="wallet">(<?php echo cl_money($me['wallet']); ?>)</b>
								</span>
							</a>
							<a class="dropdown-item" href="<?php echo cl_link("ads"); ?>" data-spa="true">
								<span class="flex-item dropdown-item-icon">
									<?php echo cl_ikon('feed'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate('Advertising'); ?>
								</span>
							</a>
							<a class="dropdown-item" href="<?php echo cl_link("affiliates"); ?>" data-spa="true">
								<span class="flex-item dropdown-item-icon">
									<?php echo cl_ikon('support-alt'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate('Affiliates'); ?>
								</span>
							</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="<?php echo cl_link("settings"); ?>" data-spa="true">
								<span class="flex-item dropdown-item-icon">
									<?php echo cl_ikon('settings'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate('Profile settings'); ?>
								</span>
							</a>
							<?php if ($cl["theme_mode"] == "N"): ?>
								<a class="dropdown-item" href="<?php echo cl_link("light_theme"); ?>">
									<span class="flex-item dropdown-item-icon">
										<?php echo cl_ikon('sun'); ?>
									</span>
									<span class="flex-item">
										<?php echo cl_translate('Light theme'); ?>
									</span>
								</a>
							<?php else: ?>
								<a class="dropdown-item" href="<?php echo cl_link("dark_theme"); ?>">
									<span class="flex-item dropdown-item-icon">
										<?php echo cl_ikon('night-mode'); ?>
									</span>
									<span class="flex-item">
										<?php echo cl_translate('Dark theme'); ?>
									</span>
								</a>
							<?php endif; ?>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="<?php echo cl_link("logout"); ?>">
								<span class="flex-item dropdown-item-icon">
									<?php echo cl_ikon('exit'); ?>
								</span>
								<span class="flex-item">
									<?php echo cl_translate('Logout'); ?>
								</span>
							</a>
						</div>
					</span>
				</li>
			</ul>
		</div>
		<div class="follow-suggestion">
			<div class="follow-suggestion__header">
				<h4>
					<?php echo cl_translate("Who to follow"); ?>
				</h4>
			</div>
			<?php if (not_empty($cl['follow_suggestion'])): ?>
				<div class="follow-suggestion__body">
					<?php foreach ($cl['follow_suggestion'] as $row): ?>
						<div class="follow-suggestion__item">
							<div class="flex-cr">
								<div class="avatar">
									<img src="<?php echo($row['avatar']); ?>" alt="avatar">
								</div>
								<div class="user-info-holder">
									<h4>
										<span class="user-name-holder <?php if ($row['verified'] == '1') {echo('verified-badge');} ?>">
											<?php echo cl_croptxt($row['name'], 15, '..'); ?>
										</span>
									</h4>
									<a href="<?php echo($row['url']); ?>" data-spa="true" data-uinfo-lbox="<?php echo($row['id']); ?>" data-toggle="popover" data-placement="top">
										<?php echo($row['username']); ?>
									</a>
								</div>
							</div>
						</div>
					<?php endforeach; ?>
				</div>
				<div class="follow-suggestion__footer">
					<a href="<?php echo cl_link("suggested"); ?>" data-spa="true">
						<?php echo cl_translate("Show more"); ?>
					</a>
				</div>
			<?php else: ?>
				<div class="follow-suggestion__placeholder">
					<?php echo cl_translate("Here will be a list of the most recommended people to follow"); ?>
				</div>
			<?php endif; ?>
		</div>
		<div class="mobile-sb-footer">
			<?php echo cl_template('main/footer'); ?>
		</div>
		<div class="publish-post-btn">
			<button class="btn btn-custom main-inline lg btn-block" data-toggle="modal" data-target="#add_new_post">
				<span class="d-inline-flex flex-wn align-items-center">
					<span class="flex-item btn-icon">
						<?php echo cl_ikon('feather'); ?>
					</span>
					<span class="flex-item">
						<?php echo cl_translate('New post'); ?>
					</span>
				</span>
			</button>
		</div>
	</div>
</div>

