<div class="left-sb-container sidebar" data-app="left-sidebar">
	<div class="sidebar__inner">
		<div class="guest-welcome">
			<div class="login-form">
				<?php echo cl_template('auth/login'); ?>
			</div>
		</div>
	</div>
</div>

<?php echo cl_template('auth/register'); ?>

<?php echo cl_template('auth/reset_password'); ?>

<?php if (not_empty($cl['em_code'])): ?>
	<?php echo cl_template('auth/new_password'); ?>
<?php endif; ?>

<?php echo cl_template('auth/scripts/app_master_script'); ?>