<div class="modal report-modal vh-center" tabindex="-1" role="dialog" data-app="report-profile-app">
    <div class="modal-dialog" role="document" id="cl-report-profile-vue-app">
        <div class="modal-content">
            <div class="modal-header">
                <div class="main---mh--block">
                    <h5 class="modal-title">
                        <?php echo cl_translate("Report this profile"); ?>
                    </h5>
                    <span class="dismiss-modal" data-dismiss="modal">
                        <?php echo cl_ikon('close'); ?>
                    </span>
                </div>
            </div>
            <div class="modal-body">
                <form class="form">
                    <div class="form-group no-mb">
                        <label class="form-label">
                            <b>
                                <?php echo cl_translate("What is the problem?"); ?>
                            </b>
                        </label>
                        <div class="radio-box-holder">
                            <?php foreach ($cl['profile_report_types'] as $i => $t): ?>
                                <div class="radio-box" v-on:click="reason = <?php echo($i); ?>">
                                    <div class="lp">
                                        <div class="icon selected" v-if="reason == <?php echo($i); ?>">
                                            <?php echo cl_ikon("checkbox"); ?>
                                        </div>
                                        <div class="icon" v-else>
                                            <?php echo cl_ikon("rectangle"); ?>
                                        </div>
                                    </div>
                                    <div class="rp">
                                        <span>
                                            <?php echo cl_translate($t); ?>
                                        </span>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        </div>
                        <hr>
                        <label class="form-label">
                            <b>
                                <?php echo cl_translate("Message to the reviewer"); ?> - <span v-bind:class="{'text-danger': (comment.length > 2900)}">({{comment.length}}/2900)</span>
                            </b>
                        </label>
                        <div class="comment-input-holder">
                            <textarea v-model.trim="comment" class="form-control" placeholder="<?php echo cl_translate("Please write briefly about the problem with this account"); ?>"></textarea>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button v-if="fe_state.submitting" disabled="true" type="buttom" class="btn btn-custom main-outline lg btn-block">
                    <?php echo cl_translate("Please wait"); ?>
                </button>
                <button v-else v-bind:disabled="is_invalid_form" v-on:click="send_report" type="buttom" class="btn btn-custom main-outline lg btn-block">
                    <?php echo cl_translate("Send report!"); ?>
                </button>
            </div>
        </div>
    </div>
</div>