<div class="modal fadeIn vh-center" data-app="auth-newpass" tabindex="-1" role="dialog" aria-labelledby="new_password_window" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="auth-modal-window">
                	<form class="form" id="cl-savepass-vue-app" v-on:submit="submit_form($event)" autocomplete="off">
                		<div class="form-title">
                			<div class="logo">
                				<a href="<?php echo cl_link("/"); ?>">
									<img src="{%config site_logo%}" alt="Logo">
								</a>
                			</div>
                			<h4><?php echo cl_translate("New password"); ?></h4>
                			<p>
                               <?php echo cl_translate("To update your password, enter a new one below. Your password must be at least 6 characters. Use uppercase and lowercase letters, numbers and special characters, for example (? $% # @)"); ?> 
                			</p>
                		</div>
	                	<div class="form-group">
                            <label><?php echo cl_translate("Password"); ?></label>
                            <input v-model.trim.lazy="$v.password.$model" type="password" name="password" class="form-control" placeholder="<?php echo cl_translate("Enter new password"); ?>">
                            <div class="invalid-main-feedback" v-if="is_valid_password">
                                {{invalid_feedback_pass}}
                            </div>
                        </div>
                        <div class="form-group">
                            <label><?php echo cl_translate("Repeat password"); ?></label>
                            <input v-model.trim="$v.password2.$model" type="password" name="conf_pass" class="form-control" placeholder="<?php echo cl_translate("Confirm new password"); ?>">
                            <div class="invalid-main-feedback" v-if="is_valid_password2">
                                {{invalid_feedback_pass2}}
                            </div>
                        </div>
                        <div class="form-group" v-if="process_failed">
                            <div class="invalid-main-feedback">
                                <?php echo cl_translate("An error occurred while trying to save the new password, please check that the data you entered is correct and try again!"); ?>
                            </div>
                        </div>
	                	<div class="form-group no-mb">
                            <button v-if="submitting != true" v-bind:disabled="is_valid_form != true" class="btn btn-custom main-inline lg btn-block">
                                <?php echo cl_translate("Save new password"); ?>
                            </button>
                            <button v-else disabled="true" type="button" class="btn btn-custom main-inline lg btn-block">
                                <?php echo cl_translate("Please wait"); ?>
                            </button>
						</div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['em_code'],'none'); ?>" name="em_code">
	                </form>
                </div>
            </div>
        </div>
    </div>
</div>