<?php if ($cl['li']['advertising']): ?>
	<?php echo cl_template('timeline/ad'); ?>
<?php else: ?>
	<div class="post-list-item" data-list-item="<?php echo($cl['li']['id']); ?>" data-post-offset="<?php echo($cl['li']['offset_id']); ?>" <?php echo fetch_or_get($cl['li']['attrs'],''); ?>>
		<?php if (not_empty($cl['li']['me_blocked'])): ?>
			<div class="post-placeholder">
				<div class="d-flex flex-wn align-items-center">
					<div class="flex-item">
						<div class="icon">
							<?php echo cl_ikon("not-allowed"); ?>
						</div>
					</div>
					<div class="felx-item">
						<p>
							<?php echo cl_translate("This user ({@uname@}) has blocked you from accessing their posts", array(
								"uname" => cl_html_el("a", $cl['li']['owner']['username'], array(
									"href" => $cl['li']['owner']['url'],
									"data-spa" => "true"
								))
							)); ?>
						</p>
					</div>
				</div>
			</div>
		<?php elseif (empty($cl['li']['can_see'])): ?>
			<div class="post-placeholder">
				<div class="d-flex flex-wn align-items-center">
					<div class="flex-item">
						<div class="icon">
							<?php echo cl_ikon("eye-crossed"); ?>
						</div>
					</div>
					<div class="felx-item">
						<p>
							<?php echo cl_translate("Only followers of this user ({@uname@}) can see their posts", array(
								"uname" => cl_html_el("a", $cl['li']['owner']['username'], array(
									"href" => $cl['li']['owner']['url'],
									"data-spa" => "true"
								))
							)); ?>
						</p>
					</div>
				</div>
			</div>
		<?php else: ?>
			<?php if (not_empty($cl['li']['is_repost'])): ?>
				<div class="post-list-item-header">
					<div class="publication-repost">
						<?php echo cl_ikon('repeat'); ?>
						<?php if (not_empty($cl['li']['is_reposter'])): ?>
							<a href="<?php echo $me['url']; ?>" data-spa="true">
								<?php echo cl_translate('You reposted'); ?>
							</a>
						<?php else: ?>
							<a href="<?php echo($cl['li']['reposter']['url']); ?>" data-spa="true">
								<?php echo cl_translate('{@uname@} reposted', array('uname' => $cl['li']['reposter']['name'])) ?>
							</a>
						<?php endif; ?>
					</div>
				</div>
			<?php endif; ?>
			<div class="post-list-item-content">
				<div class="publisher-avatar">
					<div class="avatar-holder">
						<img class="lozad" data-src="<?php echo($cl['li']['owner']['avatar']); ?>">
					</div> 
				</div>
				<div class="publication-data">
					<?php if (not_empty($cl['li']['is_blocked'])): ?>
						<div class="soft-hidden-post" data-softhidden-post="<?php echo($cl['li']['id']); ?>">
							<div class="d-flex align-items-center flex-wn">
								<div class="flex-item flex-grow-1">
									<p><?php echo cl_translate('This is a message from the user you blocked'); ?></p>
								</div>
								<div class="flex-item">
									<button class="btn btn-custom main-outline sm" onclick="SMColibri.show_post(<?php echo($cl['li']['id']); ?>, 'blocked');">
										<?php echo cl_translate('View'); ?>
									</button>
								</div>	
							</div>
						</div>
					<?php elseif(not_empty($cl['li']['is_reported'])): ?>
						<div class="soft-hidden-post" data-softhidden-post="<?php echo($cl['li']['id']); ?>">
							<div class="d-flex align-items-center flex-wn">
								<div class="flex-item flex-grow-1">
									<p>
										<?php echo cl_translate('This post is currently under review'); ?>	
									</p>
								</div>
								<div class="flex-item">
									<button class="btn btn-custom main-outline sm" onclick="SMColibri.show_post(<?php echo($cl['li']['id']); ?>, 'reported');">
										<?php echo cl_translate('View'); ?>
									</button>
								</div>	
							</div>
						</div>
					<?php endif; ?>
					
					<div class="publication-data-inner">
						<div class="publisher-info">
							<div class="lp">
								<a href="<?php echo($cl['li']['owner']['url']); ?>" data-spa="true" data-uinfo-lbox="<?php echo($cl['li']['owner']['id']); ?>" data-toggle="popover" data-placement="bottom">
									<b>
										<span class="user-name-holder <?php if ($cl['li']['owner']['verified'] == '1') { echo('verified-badge'); } ?>">
											<?php echo($cl['li']['owner']['name']); ?>
										</span>
									</b>
									<span>
										<?php echo($cl['li']['owner']['username']); ?>	
									</span>
								</a>
							</div>
							<div class="rp">
								<span class="posted-time">
									<?php echo cl_ikon('calendar'); ?>
									<time>
										<?php echo($cl['li']['time']); ?>
									</time>
								</span>
							</div>
						</div>

						<?php if ($cl['li']['target'] == 'pub_reply' && not_empty($cl['li']['reply_to'])): ?>
							<div class="publication-target">
								<?php if (not_empty($cl['li']['reply_to']['is_owner'])): ?>
									<div class="post-reply">
										<span>
											<?php echo cl_translate('In response to your {@post_url@}', array(
												'post_url' => cl_html_el('a', cl_translate('post'), array(
													'href' => $cl['li']['reply_to']['thread_url'],
													'data-spa' => 'true'
												))
											)); ?>
										</span>
									</div>
								<?php else: ?>
									<div class="post-reply">
										<span>
											<?php
												$text_temp = 'In response {@uname@} to his {@post_url@}';

												if ($cl['li']['reply_to']['gender'] == 'F') {
													$text_temp = 'In response {@uname@} to her {@post_url@}';
												}

												echo cl_translate($text_temp, array(
													'uname' => cl_html_el('a', $cl['li']['reply_to']['name'], array(
														'href' => $cl['li']['reply_to']['url'],
														'data-spa' => 'true'
													)),
													'post_url' => cl_html_el('a', cl_translate('publication'), array(
														'href' => $cl['li']['reply_to']['thread_url'],
														'data-spa' => 'true'
													))
												)); 
											?>
										</span>
									</div>
								<?php endif; ?>
							</div>
						<?php endif; ?>
						
						<div class="publication-content">
							<?php if (not_empty($cl['li']['text'])): ?>
								<?php 
									$cl['li']['text'] = cl_rn2br($cl['li']['text']);
									$cl['li']['text'] = cl_strip_brs($cl['li']['text']);
								?>
								<div class="publication-text">
									<p class="pub-text">
										<?php echo($cl['li']['text']); ?>
									</p>
								</div>
							<?php endif; ?>

							<?php if ($cl['li']['type'] == 'image' && not_empty($cl['li']['media'])): ?>
								<?php if (count($cl['li']['media']) == 1): ?>
									<div class="lozad-media" data-lozad-media="loading">
										<div class="publication-image">
											<a href="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'],'')); ?>" class="fbox-media">
												<img onload="cl_load_media(this);" onerror="cl_load_media(this);" class="lozad" data-src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'],'')); ?>" alt="Picture">
											</a>
										</div>
										<div class="lozad-preloader" data-lozad-preloader="icon">
											<img class="lozad" src="<?php echo cl_get_media('upload/default/image.png'); ?>" alt="IMG">
										</div>
									</div>
								<?php else: ?>
									<div class="publication-images-collage">
										<?php foreach ($cl['li']['media'] as $i => $row): ?>
											<a href="<?php echo cl_get_media($row['src']); ?>" class="fbox-media" data-fancybox="fbox-media-<?php echo($cl['li']['id']); ?>">
												<div class="image-collage-item">
													<div class="lozad-media" data-lozad-media="loading">
														<div class="publication-image">
															<img onload="cl_load_media(this);" onerror="cl_load_media(this);" class="d-block w-100 lozad" data-src="<?php echo cl_get_media($row['x']['image_thumb']); ?>" alt="Image">
														</div>
														<div class="lozad-preloader" data-lozad-preloader="icon">
															<div class="icon">
																<?php echo cl_ikon("image"); ?>
															</div>
														</div>
													</div>
												</div>
											</a>
										<?php endforeach; ?>
									</div>
								<?php endif; ?>
							<?php elseif($cl['li']['type'] == 'video' && not_empty($cl['li']['media'])): ?>
								<div class="lozad-media" data-lozad-media="loading">
									<div class="publication-image">
										<a href="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'],'')); ?>" class="fbox-media">
											<img class="lozad" onload="cl_load_media(this);" onerror="cl_load_media(this);" src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['x']['poster_thumb'],'')); ?>" alt="Video">
											<div class="video-icon">
												<span>
													<?php echo cl_ikon("play"); ?>
												</span>
											</div>
										</a>
								    </div>
									<div class="lozad-preloader" data-lozad-preloader="icon">
										<div class="icon">
											<?php echo cl_ikon("video"); ?>
										</div>
									</div>
								</div>
							<?php elseif($cl['li']['type'] == 'audio' && not_empty($cl['li']['media'])): ?>
								<div class="publication-audio">
									<audio controls preload="metadata">
								        <source src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'],'')); ?>" type="audio/mpeg">
								        <source src="<?php echo cl_get_media(fetch_or_get($cl['li']['media'][0]['src'],'')); ?>" type="audio/wav">
								    </audio>
								</div>
							<?php elseif($cl['li']['type'] == 'gif' && not_empty($cl['li']['media'])): ?>
								<div class="lozad-media" data-lozad-media="loading">
									<div class="publication-image">
										<a href="<?php echo fetch_or_get($cl['li']['media'][0]['src'],''); ?>" class="fbox-media">
											<img onload="cl_load_media(this);" onerror="cl_load_media(this);" class="lozad" data-src="<?php echo fetch_or_get($cl['li']['media'][0]['src'],''); ?>" alt="GIF-Image">
										</a>
									</div>
									<div class="lozad-preloader" data-lozad-preloader="icon">
										<div class="lozad-preloader" data-lozad-preloader="icon">
											<img class="lozad" src="<?php echo cl_get_media('upload/default/gif.png'); ?>" alt="IMG">
										</div>
									</div>
								</div>
							<?php elseif($cl['li']['type'] == 'poll' && not_empty($cl['li']['poll'])): ?>
								<div class="publication-poll-data" data-post-poll="<?php echo($cl['li']['id']); ?>" data-status="<?php echo($cl['li']['poll']['has_voted']); ?>">
									<div class="publication-poll-data-inner">
										<?php foreach ($cl['li']['poll']['options'] as $i => $poll_data): ?>
											<div class="poll-option-bar" onclick="SMColibri.vote_poll(<?php echo($cl['li']['id']); ?>, <?php echo($i); ?>);" data-poll-option="<?php echo($i); ?>">
												<div class="bar-icon">
													<?php echo cl_ikon("ok-circle"); ?>
												</div>
												<div class="bar-text">
													<p>
														<?php echo $poll_data["option"]; ?>
													</p>
												</div>
												<div class="bar-num">
													<b>
														<?php if (not_empty($cl['li']['poll']['has_voted'])): ?>
															<?php echo $poll_data["percentage"]; ?>%
														<?php endif; ?>
													</b>
												</div>

												<?php if (not_empty($cl['li']['poll']['has_voted'])): ?>
													<span class="bar-slider" style="width: <?php echo $poll_data["percentage"]; ?>%;"></span>
												<?php else: ?>
													<span class="bar-slider"></span>
												<?php endif; ?>
											</div>
										<?php endforeach; ?>
									</div>
								</div>
							<?php elseif(not_empty($cl['li']['og_data'])): ?>
								<?php if (not_empty($cl['li']['og_data']['video_embed'])): ?>
									<div class="publication-og-data">
										<div class="publication-og-data-inner embeded-iframe">
											<div class="og-image">
												<div class="lozad-media" data-lozad-media="loading">
													<a href="<?php echo($cl['li']['og_data']['video_embed']); ?>" class="fbox-media">
														<img onload="cl_load_media(this);" onerror="cl_load_media(this);" class="lozad" data-src="<?php echo($cl['li']['og_data']['image']); ?>" alt="Video">
														<div class="video-icon">
															<span>
																<?php echo cl_ikon("play"); ?>
															</span>
														</div>
													</a>
													<div class="lozad-preloader" data-lozad-preloader="icon">
														<div class="icon">
															<?php echo cl_ikon("video"); ?>
														</div>
													</div>
												</div>
											</div>
											<div class="og-url-data">
												<h5>
													<?php echo($cl['li']['og_data']['title']); ?>
												</h5>
												<?php if (not_empty($cl['li']['og_data']['description'])): ?>
													<p>
														<?php echo($cl['li']['og_data']['description']); ?>
													</p>
												<?php else: ?>
													<p>
														<a target="_blank" href="<?php echo($cl['li']['og_data']['video_embed']); ?>">
															<?php echo($cl['li']['og_data']['video_embed']); ?>
														</a>
													</p>
												<?php endif; ?>
											</div>
										</div>
									</div>
								<?php elseif(not_empty($cl['li']['og_data']['google_maps_embed'])): ?>
									<div class="publication-og-data">
										<div class="publication-og-data-inner embeded-iframe">
											<div class="og-image">
												<div class="lozad-media" data-lozad-media="loading">
													<a href="<?php echo($cl['li']['og_data']['url']); ?>" class="fbox-media">
														<img onload="cl_load_media(this);" onerror="cl_load_media(this);" class="lozad" data-src="<?php echo($cl['li']['og_data']['image']); ?>" alt="Video">
														<div class="video-icon">
															<span>
																<?php echo cl_ikon("map"); ?>
															</span>
														</div>
													</a>
													<div class="lozad-preloader" data-lozad-preloader="icon">
														<div class="icon">
															<?php echo cl_ikon("map"); ?>
														</div>
													</div>
												</div>
											</div>
											<div class="og-url-data">
												<h5>
													<?php echo($cl['li']['og_data']['title']); ?>
												</h5>

												<?php if (not_empty($cl['li']['og_data']['description'])): ?>
													<p>
														<?php echo($cl['li']['og_data']['description']); ?>
													</p>
												<?php endif; ?>
											</div>
										</div>
									</div>
								<?php else: ?>
									<div class="publication-og-data">
										<div class="publication-og-data-inner link" data-href="<?php echo($cl['li']['og_data']['url']); ?>">
											<?php if (not_empty($cl['li']['og_data']['image'])): ?>
												<div class="og-image">
													<img src="<?php echo($cl['li']['og_data']['image']); ?>" alt="IMG">
												</div>
											<?php endif; ?>
											
											<div class="og-url-data">
												<h5>
													<?php echo($cl['li']['og_data']['title']); ?>
												</h5>
												<p>
													<?php echo($cl['li']['og_data']['description']); ?>
												</p>
												<a href="<?php echo($cl['li']['og_data']['url']); ?>" target="_blank">
													<?php echo($cl['li']['og_data']['url']); ?>
												</a>
											</div>
										</div>
									</div>
								<?php endif; ?>
							<?php endif; ?>
						</div>
						
						<div class="publication-footer-ctrls">
							<button class="ctrls-item">
								<a class="icon" href="<?php echo $cl['li']['url']; ?>" data-spa="true">
									<span class="icon">
										<?php echo cl_ikon('chat-alt'); ?>
									</span>
									<span class="num"><?php echo $cl['li']['replys_count']; ?></span>
								</a>
							</button>

							<?php if (empty($cl['li']['has_liked'])): ?>
								<button class="ctrls-item" onclick="SMColibri.like_post('<?php echo $cl['li']['id']; ?>', this);">
									<span class="icon">
										<?php echo cl_ikon('favourite'); ?>
									</span>
									<span class="num" data-an="likes-count">
										<?php echo $cl['li']['likes_count']; ?>
									</span>
								</button>
							<?php else: ?>
								<button class="ctrls-item liked" onclick="SMColibri.like_post('<?php echo $cl['li']['id']; ?>', this);">
									<span class="icon">
										<?php echo cl_ikon('favourite'); ?>
									</span>
									<span class="num" data-an="likes-count">
										<?php echo $cl['li']['likes_count']; ?>
									</span>
								</button>
							<?php endif; ?>
							
							<?php if (empty($cl['li']['has_reposted'])): ?>
								<button onclick="SMColibri.repost('<?php echo $cl['li']['id']; ?>', this);" class="ctrls-item" data-an="repost-ctrl">
									<span class="icon">
										<?php echo cl_ikon('repeat'); ?>
									</span>
									<span class="num" data-an="reposts-count">
										<?php echo $cl['li']['reposts_count']; ?>
									</span>
								</button>
							<?php else: ?>
								<button onclick="SMColibri.repost('<?php echo $cl['li']['id']; ?>', this);" class="ctrls-item reposted" data-an="repost-ctrl">
									<span class="icon">
										<?php echo cl_ikon('repeat'); ?>
									</span>
									<span class="num" data-an="reposts-count">
										<?php echo $cl['li']['reposts_count']; ?>
									</span>
								</button>
							<?php endif; ?>

							<button class="ctrls-item" onclick="SMColibri.share_post('<?php echo $cl['li']['url']; ?>','<?php echo urlencode($cl['li']['url']); ?>');">
								<span class="icon">
									<?php echo cl_ikon('share'); ?>
								</span>
							</button>
							<button class="ctrls-item dropleft">
								<a href="#" class="dropdown-toggle icon" data-toggle="dropdown">
									<?php echo cl_ikon('chevron-down'); ?>
								</a>
								<div class="dropdown-menu dropdown-icons">
									<a class="dropdown-item" href="<?php echo $cl['li']['url']; ?>" data-spa="true">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon('arrow-right-top'); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Show thread'); ?>
										</span>
									</a>
									<?php if (not_empty($cl['li']['can_delete'])): ?>
										<a onclick="SMColibri.delete_post('<?php echo $cl['li']['id']; ?>');" class="dropdown-item col-red" href="javascript:void(0);">
											<span class="flex-item dropdown-item-icon">
												<?php echo cl_ikon('bin'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate('Delete'); ?>
											</span>
										</a>
									<?php endif; ?>
									<a onclick="SMColibri.show_likes('<?php echo $cl['li']['id']; ?>');" class="dropdown-item" href="javascript:void(0);">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon('favourite'); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Show likes'); ?>
										</span>
									</a>
									<a class="dropdown-item" href="javascript:void(0);">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon('bookmark'); ?>
										</span>
										<span class="flex-item" onclick="SMColibri.bookmark_post('<?php echo $cl['li']['id']; ?>', this);">
											<?php echo ((empty($cl['li']['has_saved'])) ? cl_translate('Bookmark') : cl_translate('Unbookmark')); ?>
										</span>
									</a>
									<a data-clipboard-text="<?php echo($cl['li']['url']); ?>" class="dropdown-item clip-board-copy" href="javascript:void(0);">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon('copy'); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Copy link'); ?>
										</span>
									</a>
									<?php if (empty($cl['li']['is_owner'])): ?>
										<a onclick="SMColibri.report_post(<?php echo($cl['li']['id']); ?>);" class="dropdown-item" href="javascript:void(0);">
											<span class="flex-item dropdown-item-icon">
												<?php echo cl_ikon('flag'); ?>
											</span>
											<span class="flex-item">
												<?php echo cl_translate('Report post'); ?>
											</span>
										</a>
									<?php endif; ?>
									<div class="dropdown-divider"></div>
									<a onclick="SMColibri.share_post('<?php echo $cl['li']['url']; ?>','<?php echo urlencode($cl['li']['url']); ?>');" class="dropdown-item" href="javascript:void(0);">
										<span class="flex-item dropdown-item-icon">
											<?php echo cl_ikon('share'); ?>
										</span>
										<span class="flex-item">
											<?php echo cl_translate('Share'); ?>
										</span>
									</a>
								</div>
							</button>
						</div>
					</div>	
				</div>
			</div>
		<?php endif;?>
	</div>
	<?php if (not_empty($cl["gads_horiz"])): ?>
		<?php if (cl_show_feed_gad()): ?>
			<div class="cl-google-ads centered">
				<?php echo $cl["gads_horiz"]; ?>
			</div>
		<?php endif; ?>
	<?php endif; ?>
<?php endif; ?>