<div class="hashtags-list-item">
	<a class="link" href="<?php echo($cl['li']['url']); ?>" data-spa="true">
		<span class="hash">#</span>
		<span class="hashtag-info">
			<b class="tag">
				<?php echo($cl['li']['hashtag']); ?>
			</b> 
			<span class="total"><?php echo($cl['li']['total']); ?> <?php echo cl_translate('Posts'); ?></span>
		</span>
		<span class="icon">
			<?php echo cl_ikon('arrow-right'); ?>
		</span>
	</a>
</div>