<div class="timeline-container">
	<div class="timeline-header" data-el="tl-header">
		<div class="lp">
			<div class="nav-link-holder">
				<a href="<?php echo cl_link("settings"); ?>" data-spa="true">
					<?php echo cl_translate("Profile settings"); ?>
				</a>
			</div>
		</div>
		<div class="cp">
			<a href="<?php echo cl_link("home"); ?>">
				<img src="{%config site_logo%}" alt="Logo">
			</a>
		</div>
		<div class="rp">
			<div class="nav-link-holder">
				<span class="go-back" onclick="SMColibri.go_back();">
					<?php echo cl_ikon('arrow-left'); ?>
				</span>
			</div>
		</div>
	</div>

	<div class="main--profile-settings-container">
		<div class="profile-settings-nav">
			<div class="nav-list-itemset-title">
				<h4><?php echo cl_translate("General profile settings"); ?></h4>
			</div>
			<div class="nav-list-item" onclick="CLSettings.open('name-settings');">
				<div class="lp">
					<span class="preview-label">
						<?php echo cl_translate("Username"); ?>
					</span>
					<span class="preview-value">
						<?php echo $me['name']; ?> - <small><?php echo $me['username']; ?></small>
					</span>
				</div>
				<div class="rp">
					<?php echo cl_ikon("edit"); ?>
				</div>
			</div>
			<div class="nav-list-item" onclick="CLSettings.open('email-settings');">
				<div class="lp">
					<span class="preview-label"><?php echo cl_translate("Email address"); ?></span>
					<span class="preview-value">
						<?php echo $me['email']; ?>
					</span>
				</div>
				<div class="rp">
					<?php echo cl_ikon("envelope"); ?>
				</div>
			</div>
			<div class="nav-list-item" onclick="CLSettings.open('url-settings');">
				<div class="lp">
					<span class="preview-label"><?php echo cl_translate("Website URL address"); ?></span>
					<span class="preview-value">
						<?php if (empty($me['website'])): ?>
							<?php echo cl_translate("You have not yet determined the URL of your site"); ?>
						<?php else: ?>
							<?php echo $me['website']; ?>
						<?php endif; ?>
					</span>
				</div>
				<div class="rp">
					<?php echo cl_ikon("link"); ?>
				</div>
			</div>
			<div class="nav-list-item" onclick="CLSettings.open('bio-settings');">
				<div class="lp">
					<span class="preview-label"><?php echo cl_translate("About you"); ?></span>
					<span class="preview-value">
						<?php if (empty($me['about'])): ?>
							<?php echo cl_translate("The field with information about you is still empty"); ?>
						<?php else: ?>
							<?php echo $me['about']; ?>
						<?php endif; ?>
					</span>
				</div>
				<div class="rp">
					<?php echo cl_ikon("info"); ?>
				</div>
			</div>
			<div class="nav-list-item" onclick="CLSettings.open('gender-settings');">
				<div class="lp">
					<span class="preview-label"><?php echo cl_translate("Your gender"); ?></span>
					<span class="preview-value">
						<?php if ($me['gender'] == 'M'): ?>
							<?php echo cl_translate("Male"); ?>
						<?php else: ?>
							<?php echo cl_translate("Female"); ?>
						<?php endif; ?>
					</span>
				</div>
				<div class="rp">
					<?php echo cl_ikon("people"); ?>
				</div>
			</div>
			<div class="nav-list-itemset-title">
				<h4><?php echo cl_translate("User password"); ?></h4>
			</div>
			<div class="nav-list-item" onclick="CLSettings.open('password-settings');">
				<div class="lp">
					<span class="preview-label"><?php echo cl_translate("My password"); ?></span>
					<span class="preview-value">
						<?php echo cl_translate("Click to set your account password"); ?>
					</span>
				</div>
				<div class="rp">
					<?php echo cl_ikon("lock"); ?>
				</div>
			</div>
			<div class="nav-list-itemset-title">
				<h4><?php echo cl_translate("Language and Country"); ?></h4>
			</div>
			<div class="nav-list-item" onclick="CLSettings.open('language-settings');">
				<div class="lp">
					<span class="preview-label"><?php echo cl_translate("Display language"); ?></span>
					<span class="preview-value">
						<?php echo $me['display_lang']; ?>
					</span>
				</div>
				<div class="rp">
					<?php echo cl_ikon("language"); ?>
				</div>
			</div>
			<div class="nav-list-item" onclick="CLSettings.open('country-settings');">
				<div class="lp">
					<span class="preview-label"><?php echo cl_translate("The country in which you live"); ?></span>
					<span class="preview-value">
						<?php echo($me['country_name']); ?>
					</span>
				</div>
				<div class="rp">
					<?php echo cl_ikon("flag"); ?>
				</div>
			</div>
			<div class="nav-list-itemset-title">
				<h4><?php echo cl_translate("Account verification"); ?></h4>
			</div>
			<div class="nav-list-item" onclick="CLSettings.open('verif-settings');">
				<div class="lp">
					<span class="preview-label"><?php echo cl_translate("Verify my account"); ?></span>
					<span class="preview-value">
						<?php echo cl_translate("Click to submit a verification request"); ?> 
					</span>
				</div>
				<div class="rp">
					<?php echo cl_ikon("verified"); ?>
				</div>
			</div>
			<div class="nav-list-itemset-title">
				<h4><?php echo cl_translate("Account privacy settings"); ?></h4>
			</div>
			<div class="nav-list-item" onclick="CLSettings.open('privacy-settings');">
				<div class="lp">
					<span class="preview-label">
						<?php echo cl_translate("Account privacy"); ?>
					</span>
					<span class="preview-value">
						<?php echo cl_translate("Click to set your account privacy"); ?>
					</span>
				</div>
				<div class="rp">
					<?php echo cl_ikon("shield"); ?>
				</div>
			</div>
			<div class="nav-list-item" onclick="CLSettings.open('notifs-settings');">
				<div class="lp">
					<span class="preview-label">
						<?php echo cl_translate("Notifications"); ?>
					</span>
					<span class="preview-value">
						<?php echo cl_translate("Click to set up account notifications"); ?>
					</span>
				</div>
				<div class="rp">
					<?php echo cl_ikon("bell"); ?>
				</div>
			</div>
			<?php if (not_empty($cl["blocked_users"])): ?>
				<div class="nav-list-item" onclick="CLSettings.open('blocks-settings');">
					<div class="lp">
						<span class="preview-label">
							<?php echo cl_translate("Blocked users"); ?>
						</span>
						<span class="preview-value">
							<?php echo cl_translate("Click to manage blocked users"); ?>
						</span>
					</div>
					<div class="rp">
						<?php echo cl_ikon("not-allowed"); ?>
					</div>
				</div>
			<?php endif; ?>
			<div class="nav-list-itemset-title">
				<h4><?php echo cl_translate("My account information"); ?></h4>
			</div>
			<div class="nav-list-item" onclick="CLSettings.open('account-info');">
				<div class="lp">
					<span class="preview-label"><?php echo cl_translate("Download my information"); ?></span>
					<span class="preview-value">
						<?php echo cl_translate("Please choose what information you want to download"); ?> 
					</span>
				</div>
				<div class="rp">
					<?php echo cl_ikon("download"); ?>
				</div>
			</div>
			<div class="nav-list-itemset-title">
				<h4><?php echo cl_translate("Delete profile"); ?></h4>
			</div>
			<div class="nav-list-item nav-list-item-delete" onclick="CLSettings.open('delete-settings');">
				<div class="lp">
					<span class="preview-label"><?php echo cl_translate("Delete profile"); ?></span>
					<span class="preview-value">
						<?php echo cl_translate("Click to confirm deletion of your profile"); ?> 
					</span>
				</div>
				<div class="rp">
					<?php echo cl_ikon("bin"); ?>
				</div>
			</div>
		</div>
	</div>
	<?php echo cl_template("main/includes/inline_statics/app_statics"); ?>
	<div class="modals-container">
		<?php echo cl_template('settings/modals/edit_profile_name');?>

		<?php echo cl_template('settings/modals/edit_profile_email');?>

		<?php echo cl_template('settings/modals/edit_profile_siteurl');?>

		<?php echo cl_template('settings/modals/edit_profile_bio');?>

		<?php echo cl_template('settings/modals/edit_profile_gender');?>

		<?php echo cl_template('settings/modals/edit_profile_password');?>

		<?php echo cl_template('settings/modals/edit_profile_language');?>

		<?php echo cl_template('settings/modals/edit_profile_country');?>

		<?php echo cl_template('settings/modals/verify_account');?>

		<?php echo cl_template('settings/modals/edit_account_privacy');?>

		<?php echo cl_template('settings/modals/notification_settings');?>

		<?php if (not_empty($cl["blocked_users"])): ?>
			<?php echo cl_template('settings/modals/edit_account_blocks');?>
		<?php endif; ?>

		<?php echo cl_template('settings/modals/delete_account');?>

		<?php echo cl_template('settings/modals/account_information');?>

		<?php echo cl_template('settings/scripts/app_master_script');?>
	</div>
</div>



