<div class="cp-app-container" data-app="payment-gateways">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                Payment gateways
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        Control panel
                    </a>
                </li>
                <li class="active">
                    <a href="javascript:void(0);">
                        Payment gateways
                    </a>
                </li> 
            </ol>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Manage Payment gateway API settings
                    </h2>
                </div>
                <div class="body">
                    <form class="form" data-an="form">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group" data-an="paypal_api_key-input">
                                    <label>
                                        PayPal API Public key
                                    </label>
                                    <div class="form-line">
                                        <input value="{%config paypal_api_key%}" name="paypal_api_key" type="text" class="form-control" placeholder="Enter paypal API public key">
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group" data-an="paypal_api_pass-input">
                                    <label>
                                        PayPal API Secret key
                                    </label>
                                    <div class="form-line">
                                        <input value="{%config paypal_api_pass%}" name="paypal_api_pass" type="text" class="form-control" placeholder="Enter paypal API secret key">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group" data-an="paypal_mode-input">
                                    <label>
                                        PayPal Payment Mode
                                    </label>
                                    <div class="form-line">
                                        <select name="paypal_mode" class="form-control selectpicker">
                                            <option value="sandbox" <?php if($cl['config']['paypal_mode'] == 'sandbox') { echo('selected'); } ?>>Sandbox</option>
                                            <option value="live" <?php if($cl['config']['paypal_mode'] == 'live') { echo('selected'); } ?>>Live</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 no-mb">
                                <button data-an="submit-ctrl" type="submit" class="btn bg-blue btn-block btn-lg waves-effect ttup">
                                    Save changes
                                </button>
                            </div>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/payment_gateways/scripts/app_master_script'); ?>