<div class="modal fade vh-center" data-app="cl-password-settings" tabindex="-1" role="dialog" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="form" id="cl-password-settings-vue-app" v-on:submit="submit_form($event)">
                <div class="modal-header">
                    <div class="main---mh--block">
                        <h5 class="modal-title">
                            <?php echo cl_translate("Profile password"); ?>
                        </h5>
                        <span class="dismiss-modal" data-dismiss="modal">
                            <?php echo cl_ikon('close'); ?>
                        </span>
                    </div>
                </div>
                <div class="modal-body">
                    <div class="popup-modal-form">
                        <div class="form-group">
                            <label>
                                <?php echo cl_translate("Current password"); ?>
                            </label>
                            <input v-model.trim.lazy="$v.password1.$model" name="curr_password" type="password" class="form-control" placeholder="<?php echo cl_translate("Enter your current password"); ?>">
                            <div class="invalid-main-feedback" v-if="is_valid_password1">
                                {{invalid_feedback_pass1}}
                            </div>
                        </div>
                        <div class="form-group">
                            <label>
                                <?php echo cl_translate("New password"); ?>
                            </label>
                            <input v-model.trim.lazy="$v.password2.$model" name="new_password" type="password" class="form-control" placeholder="<?php echo cl_translate("Enter new password"); ?>">
                            <div class="invalid-main-feedback" v-if="is_valid_password2">
                                {{invalid_feedback_pass2}}
                            </div>
                        </div>
                        <div class="form-group">
                            <label>
                                <?php echo cl_translate("Confirm new password"); ?>
                            </label>
                            <input v-model.trim="$v.password3.$model" name="new_conf_pass" type="password" class="form-control" placeholder="<?php echo cl_translate("Confirm new password"); ?>">
                            <div class="invalid-main-feedback" v-if="is_valid_password3">
                                {{invalid_feedback_pass3}}
                            </div>
                        </div>
                        <div class="form-group no-mb" v-if="unsuccessful_attempt">
                            <div class="invalid-main-feedback">
                                <?php echo cl_translate("Something went wrong while trying to save your changes, please try again later"); ?>
                            </div>
                        </div>
                        <div class="form-group no-mb" v-else>
                            <p class="form-info-label">
                                <?php echo cl_translate("Before changing your current password, please follow these tips: Indicate the minimum length (6 characters). Use uppercase and lowercase letters. Use numbers and special characters (&%$)"); ?>
                            </p>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </div>
                </div>
                <div class="modal-footer">
                    <button v-if="submitting != true" v-bind:disabled="$v.$invalid == true" type="submit" class="btn btn-custom main-inline md">
                        <?php echo cl_translate("Save changes"); ?>
                    </button>
                    <button v-else disabled="true" type="button" class="btn btn-custom main-inline md">
                        <?php echo cl_translate("Please wait"); ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>