<div class="modal fade vh-center" data-app="cl-name-settings" tabindex="-1" role="dialog" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="form" id="cl-name-settings-vue-app" v-on:submit="submit_form($event)">
                <div class="modal-header">
                    <div class="main---mh--block">
                        <h5 class="modal-title">
                            <?php echo cl_translate("Username"); ?>
                        </h5>
                        <span class="dismiss-modal" data-dismiss="modal">
                            <?php echo cl_ikon('close'); ?>
                        </span>
                    </div>
                </div>
                <div class="modal-body">
                    <div class="popup-modal-form">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label><?php echo cl_translate("Username"); ?></label>
                                    <input v-model.trim="$v.uname.$model" name="uname" type="text" class="form-control" placeholder="<?php echo cl_translate("Enter first name"); ?>">
                                    <div class="invalid-main-feedback" v-if="is_valid_uname">
                                        {{invalid_feedback_uname}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label><?php echo cl_translate("First name"); ?></label>
                                    <input v-model.trim="$v.fname.$model" name="fname" type="text" class="form-control" placeholder="<?php echo cl_translate("Enter first name"); ?>">
                                    <div class="invalid-main-feedback" v-if="is_valid_fname">
                                        {{invalid_feedback_fname}}
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group no-mb">
                                    <label><?php echo cl_translate("Last name"); ?></label>
                                    <input v-model.trim="$v.lname.$model" name="lname" type="text" class="form-control" placeholder="<?php echo cl_translate("Enter last name"); ?>">
                                    <div class="invalid-main-feedback" v-if="is_valid_lname">
                                        {{invalid_feedback_lname}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group no-mb" v-if="unsuccessful_attempt">
                            <div class="invalid-main-feedback">
                                <?php echo cl_translate("Something went wrong while trying to save your changes, please try again later"); ?>
                            </div>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </div>
                </div>
                <div class="modal-footer">
                    <button v-if="submitting != true" v-bind:disabled="$v.$invalid == true" type="submit" class="btn btn-custom main-inline md"><?php echo cl_translate("Save changes"); ?></button>
                    <button v-else disabled="true" type="button" class="btn btn-custom main-inline md">
                        <?php echo cl_translate("Please wait"); ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>