<div class="modal fade vh-center" data-app="cl-country-settings" tabindex="-1" role="dialog" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="form" id="cl-country-settings-vue-app" v-on:submit="submit_form">
                <div class="modal-header">
                    <div class="main---mh--block">
                        <h5 class="modal-title">
                            <?php echo cl_translate("Change country"); ?>
                        </h5>
                        <span class="dismiss-modal" data-dismiss="modal">
                            <?php echo cl_ikon('close'); ?>
                        </span>
                    </div>
                </div>
                <div class="modal-body">
                    <div class="popup-modal-form">
                        <div class="form-group">
                            <label>
                                <?php echo cl_translate("Choose your country"); ?>
                            </label>
                            <div class="dropdown vue-dropdown-select">
                                <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    {{countries[country]}}
                                </button>
                                <div class="dropdown-menu">
                                    <a v-for="(v,k) in countries" v-on:click="dropdown_select(k)" class="dropdown-item" href="javascript:void(0);">
                                        {{v}}
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="form-group no-mb" v-if="unsuccessful_attempt">
                            <div class="invalid-main-feedback">
                                <?php echo cl_translate("Something went wrong while trying to save your changes, please try again later"); ?>
                            </div>
                        </div>
                        <div class="form-group no-mb" v-else>
                            <p class="form-info-label">
                                <?php echo cl_translate("Choose the country in which you live. This information will be publicly displayed on your profile."); ?>
                            </p>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                        <input v-model="country" type="hidden" class="d-none" name="country">
                    </div>
                </div>
                <div class="modal-footer">
                    <button v-if="submitting != true" v-bind:disabled="$v.$invalid == true" type="submit" class="btn btn-custom main-inline md">
                        <?php echo cl_translate("Save changes"); ?>
                    </button>
                    <button v-else disabled="true" type="button" class="btn btn-custom main-inline md">
                        <?php echo cl_translate("Please wait"); ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>