<div class="modal fade vh-center" data-app="cl-notifs-settings" tabindex="-1" role="dialog" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="form" id="cl-notifs-settings-vue-app" v-on:submit="submit_form($event)">
                <div class="modal-header">
                    <div class="main---mh--block">
                        <h5 class="modal-title">
                            <?php echo cl_translate("Notification settings"); ?>
                        </h5>
                        <span class="dismiss-modal" data-dismiss="modal">
                            <?php echo cl_ikon('close'); ?>
                        </span>
                    </div>
                </div>
                <div class="modal-body">
                    <div class="popup-modal-form">
                        <div class="form-group">
                            <div class="chekbox-block-item">
                                <div class="d-flex flex-nw align-items-center justify-content-between">
                                    <div class="flex-item flex-grow-1">
                                        <span class="switch-label">
                                            <?php echo cl_translate("Liked my post"); ?>
                                        </span>
                                    </div>
                                    <div class="flex-item">
                                        <div class="switch lever-label">
                                            <label>
                                                <input name="like" type="checkbox" <?php if(not_empty($me["settings"]["notifs"]["like"])) {echo("checked");} ?>>
                                                <span class="lever switch-col-blue"></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>  
                                <p class="form-info-label">
                                    <?php echo cl_translate("Notify me when someone like my post"); ?>
                                </p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="chekbox-block-item">
                                <div class="d-flex flex-nw align-items-center justify-content-between">
                                    <div class="flex-item flex-grow-1">
                                        <span class="switch-label">
                                            <?php echo cl_translate("Followed me"); ?>
                                        </span>
                                    </div>
                                    <div class="flex-item">
                                        <div class="switch lever-label">
                                            <label>
                                                <input name="subscribe" type="checkbox" <?php if(not_empty($me["settings"]["notifs"]["subscribe"])) {echo("checked");} ?>>
                                                <span class="lever switch-col-blue"></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>  
                                <p class="form-info-label">
                                    <?php echo cl_translate("Notify me when someone followed me"); ?>
                                </p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="chekbox-block-item">
                                <div class="d-flex flex-nw align-items-center justify-content-between">
                                    <div class="flex-item flex-grow-1">
                                        <span class="switch-label">
                                            <?php echo cl_translate("Follow request"); ?>
                                        </span>
                                    </div>
                                    <div class="flex-item">
                                        <div class="switch lever-label">
                                            <label>
                                                <input name="subscribe_request" type="checkbox" <?php if(not_empty($me["settings"]["notifs"]["subscribe_request"])) {echo("checked");} ?>>
                                                <span class="lever switch-col-blue"></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>  
                                <p class="form-info-label">
                                    <?php echo cl_translate("Notify me when someone sends a follow request"); ?>
                                </p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="chekbox-block-item">
                                <div class="d-flex flex-nw align-items-center justify-content-between">
                                    <div class="flex-item flex-grow-1">
                                        <span class="switch-label">
                                            <?php echo cl_translate("Subscription acceptance"); ?>
                                        </span>
                                    </div>
                                    <div class="flex-item">
                                        <div class="switch lever-label">
                                            <label>
                                                <input name="subscribe_accept" type="checkbox" <?php if(not_empty($me["settings"]["notifs"]["subscribe_accept"])) {echo("checked");} ?>>
                                                <span class="lever switch-col-blue"></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>  
                                <p class="form-info-label">
                                    <?php echo cl_translate("Notify me when my subscription request is accepted"); ?>
                                </p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="chekbox-block-item">
                                <div class="d-flex flex-nw align-items-center justify-content-between">
                                    <div class="flex-item flex-grow-1">
                                        <span class="switch-label">
                                            <?php echo cl_translate("Replied me"); ?>
                                        </span>
                                    </div>
                                    <div class="flex-item">
                                        <div class="switch lever-label">
                                            <label>
                                                <input name="reply" type="checkbox" <?php if(not_empty($me["settings"]["notifs"]["reply"])) {echo("checked");} ?>>
                                                <span class="lever switch-col-blue"></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>  
                                <p class="form-info-label">
                                    <?php echo cl_translate("Notify me when someone replied me"); ?>
                                </p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="chekbox-block-item">
                                <div class="d-flex flex-nw align-items-center justify-content-between">
                                    <div class="flex-item flex-grow-1">
                                        <span class="switch-label">
                                            <?php echo cl_translate("Publication repost"); ?>
                                        </span>
                                    </div>
                                    <div class="flex-item">
                                        <div class="switch lever-label">
                                            <label>
                                                <input name="repost" type="checkbox" <?php if(not_empty($me["settings"]["notifs"]["repost"])) {echo("checked");} ?>>
                                                <span class="lever switch-col-blue"></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>  
                                <p class="form-info-label">
                                    <?php echo cl_translate("Notify me when someone re-posts my publication"); ?>
                                </p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="chekbox-block-item">
                                <div class="d-flex flex-nw align-items-center justify-content-between">
                                    <div class="flex-item flex-grow-1">
                                        <span class="switch-label">
                                            <?php echo cl_translate("Mentioned me"); ?>
                                        </span>
                                    </div>
                                    <div class="flex-item">
                                        <div class="switch lever-label">
                                            <label>
                                                <input name="mention" type="checkbox" <?php if(not_empty($me["settings"]["notifs"]["mention"])) {echo("checked");} ?>>
                                                <span class="lever switch-col-blue"></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>  
                                <p class="form-info-label">
                                    <?php echo cl_translate("Notify me when someone mentioned me"); ?>
                                </p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="chekbox-block-item">
                                <div class="d-flex flex-nw align-items-center justify-content-between">
                                    <div class="flex-item flex-grow-1">
                                        <span class="switch-label">
                                            <?php echo cl_translate("Visited me"); ?>
                                        </span>
                                    </div>
                                    <div class="flex-item">
                                        <div class="switch lever-label">
                                            <label>
                                                <input name="visit" type="checkbox" <?php if(not_empty($me["settings"]["notifs"]["visit"])) {echo("checked");} ?>>
                                                <span class="lever switch-col-blue"></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>  
                                <p class="form-info-label">
                                    <?php echo cl_translate("Notify me when someone visited my profile"); ?>
                                </p>
                            </div>
                        </div>
                        <div class="form-group no-mb" v-if="unsuccessful_attempt">
                            <div class="invalid-main-feedback">
                                <?php echo cl_translate("Something went wrong while trying to save your changes, please try again later"); ?>
                            </div>
                        </div>
                        <div class="form-group no-mb" v-else>
                            <p class="form-info-label">
                                <?php echo cl_translate("Choose which notifications about your (actions, events) related to your account you want to receive"); ?>
                            </p>
                        </div>
                        <input type="hidden" class="d-none" value="<?php echo fetch_or_get($cl['csrf_token'],'none'); ?>" name="hash">
                    </div>
                </div>
                <div class="modal-footer">
                    <button v-if="submitting != true" v-bind:disabled="$v.$invalid == true" type="submit" class="btn btn-custom main-inline md">
                        <?php echo cl_translate("Save changes"); ?>
                    </button>
                    <button v-else disabled="true" type="button" class="btn btn-custom main-inline md">
                        <?php echo cl_translate("Please wait"); ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>