<div class="timeline-container" data-app="suggested">
	<div class="timeline-header" data-el="tl-header">
		<div class="lp">
			<div class="nav-link-holder">
				<a href="<?php echo cl_link("suggested"); ?>" data-spa="true">
					<?php echo cl_translate("Recommendations"); ?>
				</a>
			</div>
		</div>
		<div class="cp">
			<a href="<?php echo cl_link('/'); ?>">
				<img src="{%config site_logo%}" alt="Logo">
			</a>
		</div>
		<div class="rp">
			<div class="nav-link-holder">
				<span class="go-back" onclick="SMColibri.go_back();">
					<?php echo cl_ikon('arrow-left'); ?>
				</span>
			</div>
		</div>
	</div>
	<div class="suggested--people-list-container">
		<div class="suggested-list" data-an="suggested-list">
			<?php if (not_empty($cl["users_list"])): ?>
				<?php foreach ($cl["users_list"] as $cl['li']): ?>
					<?php echo cl_template('suggested/includes/list_item'); ?>
				<?php endforeach; ?>
			<?php endif; ?>
		</div>
		<div class="load-more">
			<button class="btn btn-custom main-outline lg" data-an="load-more">
				<?php echo cl_translate("Show more"); ?>
			</button>
		</div>
	</div>

	<?php echo cl_template("main/includes/inline_statics/app_statics"); ?>
	
	<?php echo cl_template('suggested/scripts/app_master_script'); ?>
</div>