<script>
	"use strict";
	
	$(document).ready(function($) {
		var _app = new Vue({
			el: "#vue-chats-app",
			data: {
				searching: false,
				display_chats: true,
				search_query: ""
			},
			methods: {
				search_chats: function(e) {
					if (e.target.value.length >= 0) {
						var contacts    = $(this.$el).find('[data-an="contacts-list"]');
						var matches     = 0;
						var _app_       = this;
						_app_.searching = true;

						contacts.find('b.name').each(function(index, el) {

							var username = $.trim($(el).text());
							var regex    = new RegExp(e.target.value,'ig');

							if (username.search(regex) == -1) {
								$(el).parents('div[data-list-item]').addClass('hidden');
							}
							else {
								$(el).parents('div[data-list-item]').removeClass('hidden');

								matches++;
							}
						}).promise().done(function() {
							if (cl_empty(matches)) {
								_app_.display_chats = false;
							}
							else {
								_app_.display_chats = true;
							}

							_app_.searching = false;
						});
					}
					else {
						this.searching = false;
					}
				}
			}
		});
	});
</script>