<div class="cp-app-container" data-app="posts">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                Publications
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        Control panel
                    </a>
                </li>
                <li class="active">
                    <a href="javascript:void(0);">
                        Publications
                    </a>
                </li> 
            </ol>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card" data-an="info-content">
                <div class="header">
                    <h2>
                        Manage site publications
                    </h2>
                </div>
                <div class="body">
                    <div class="regular-table">
                        <table class="table table-hover no-mb">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>
                                        Post type
                                    </th>
                                    <th>
                                        Target
                                    </th>
                                    <th>
                                        Replys
                                    </th>
                                    <th>
                                        Likes
                                    </th>
                                    <th>
                                        Reposts
                                    </th>
                                    <th>
                                        Date
                                    </th>
                                    <th>
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody data-an="posts-list">
                                <?php if (not_empty($cl['posts'])): ?>
                                    <?php foreach ($cl['posts'] as $cl['li']): ?>
                                        <?php echo cl_template('cpanel/assets/publications/includes/list_item'); ?>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr>
                                        <td colspan="8">
                                            <div class="empty-table">
                                                <span class="icon">
                                                    <i class="material-icons">video_library</i>
                                                </span>
                                                <h4>
                                                    No posts found
                                                </h4>
                                                <p>
                                                    It looks like there are no posts in your database yet. All publications of your site will be displayed here.
                                                </p>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                        <div class="table-pagination">
                            <?php if (not_empty($cl['posts'])): ?>
                                <a data-an="pagination" data-dir="prev" href="javascript:void(0);" class="pagination-ctrls prev">
                                    <i class="material-icons">chevron_left</i>
                                </a>
                                <a data-an="pagination" data-dir="next" href="javascript:void(0);" class="pagination-ctrls next">
                                    <i class="material-icons">chevron_right</i>
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo cl_template('cpanel/assets/publications/scripts/app_master_script'); ?>