<div class="swift-app-container" id="cl-play-swift-vue-app" v-bind:class="{'show': status}">
    <div class="swift-data-cont">
        <div class="swift-data">
            <div class="swift-data-header">
                <div class="swift-data-sliders">
                    <div v-for="(val, index) in swift_data.swift" class="slider-item" v-on:click="slide_to(index)">
                        <span v-if="curr_swift_id == index" v-bind:style="{width: slide_bar_status + '%'}"></span>
                        <span v-else v-bind:style="{width: val.slide_bar + '%'}"></span>
                    </div>
                </div>
                <div class="swift-data-ctrls">
                    <div class="d-flex flex-row align-items-center flex-wn">
                        <div class="flex-item">
                            <div class="swift-user-info">
                                <div class="d-flex ov-h flex-row align-items-center flex-wn">
                                    <div class="flex-item">
                                        <div class="avatar">
                                            <img v-bind:src="swift_data.avatar" alt="Avatar">
                                        </div>
                                    </div>
                                    <div class="flex-item ov-h flex-grow-1">
                                        <div class="uname">
                                            <h6>
                                                <a v-bind:href="swift_data.url">{{swift_data.name}}</a> • <time>{{curr_swift.time}}</time>
                                            </h6>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="flex-item flex-grow-1">
                            <div class="ctrl-group">
                                <div class="d-flex flex-row align-items-center flex-wn justify-content-end">
                                    <div class="flex-item" v-if="swift_data.is_user && curr_swift_views > 0">
                                        <div class="swift-data-ctrl-item">
                                            <button class="dropleft">
                                                <a href="#" class="dropdown-toggle icon" data-toggle="dropdown">
                                                    <?php echo cl_ikon('eye'); ?>
                                                </a>
                                                <div class="dropdown-menu">
                                                    <div class="swift-views">
                                                        <div class="swift-views-header">
                                                            <h6>Views - ({{curr_swift_views}})</h6>
                                                        </div>
                                                        <div class="swift-views-body">
                                                            <div v-for="user in curr_swift.views" class="view-li">
                                                                <div class="d-flex flex-wn align-items-center">
                                                                    <div class="flex-item">
                                                                        <div class="avatar">
                                                                            <img v-bind:src="user.avatar" alt="Img">
                                                                        </div>
                                                                    </div>
                                                                    <div class="flex-item">
                                                                        <div class="user-name">
                                                                            <a href="#">{{user.name}}</a>
                                                                            <time>{{user.time}}</time>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="flex-item" v-if="swift_data.is_user">
                                        <div class="swift-data-ctrl-item">
                                            <button class="btn" v-on:click="delete_swift">
                                                <?php echo cl_ikon("bin"); ?>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="flex-item">
                                        <div class="swift-data-ctrl-item">
                                            <button class="btn" onclick="SMColibri.PS.play_swift.close();">
                                                <?php echo cl_ikon("close"); ?>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="swift-data-body">
                <div class="swift-data-item">
                    <div v-if="curr_swift.type == 'image'" class="swift-data-image">
                        <img v-bind:src="curr_swift.media.src" alt="swift-img" v-on:load="swift_loaded = true" v-on:error="swift_loaded = true">
                    </div>
                    <div v-else-if="curr_swift.type == 'video'" class="swift-data-video">
                        <video ref="video" v-on:loadeddata="swift_loaded = true" v-on:error="swift_loaded = true">
                            <source type="video/mp4" v-bind:src="curr_swift.media.source"/>
                            <source type="video/webm" v-bind:src="curr_swift.media.source"/>
                            <source type="video/mov" v-bind:src="curr_swift.media.source"/>
                            <source type="video/3gp" v-bind:src="curr_swift.media.source"/>
                            <source type="video/ogg" v-bind:src="curr_swift.media.source"/>
                        </video>
                    </div>
                </div>
                <button v-if="has_prev" class="swift-data-slide-ctrl prev" v-on:click="slide_prev">
                    <span>
                        <?php echo cl_ikon("chevron-left"); ?>
                    </span>
                </button>
                <button class="swift-data-slide-ctrl pause">
                    <span v-if="slide_bar_pause" v-on:click="un_pause">
                        <?php echo cl_ikon("play"); ?>
                    </span>
                    <span v-else v-on:click="do_pause">
                        <?php echo cl_ikon("pause"); ?>
                    </span>
                </button>
                <button v-if="has_next" class="swift-data-slide-ctrl next" v-on:click="slide_next">
                    <span>
                        <?php echo cl_ikon("chevron-right"); ?>
                    </span>
                </button>
            </div>
            <div class="swift-data-footer">
                <div v-if="curr_swift.text" class="swift-caption">
                    <p>{{curr_swift.text}}</p>
                </div>
            </div>
        </div>
    </div>
</div>