<script>
	"use strict";

	jQuery(document).ready(function($) {
		Vue.use(window.vuelidate.default);

		var _app           = $('[data-app="wallet"]');
		var vue_validators = window.validators;
		var SMCWallet      = new Vue({
			el: "#vue-wallet-topup-app",
			data: {
				topup_amount: "",
				submitting: false
			},
			computed: {
				is_invalid_amount: function() {
					if (this.$v.topup_amount.required && this.$v.topup_amount.$invalid) {
						return true;
					}
					else{
						return false;
					}
				},
				is_invalid_form: function() {
					if (this.$v.$invalid) {
						return true;
					}
					else {
						return false;
					}
				}
			},
			validations: {
				topup_amount: {
					required: vue_validators.required,
					is_num: vue_validators.numeric,
					min_val: vue_validators.minValue(50),
					max_val: vue_validators.maxValue(15000)
				}
			},
			methods: {
				submit_form: function(_self = false) {
					_self.preventDefault();

					let _app_ = this;

					$(_self.target).ajaxSubmit({
						url: "<?php echo cl_link("native_api/settings/topup_wallet"); ?>",
						type: 'POST',
						dataType: 'json',
						data: {amount: _app_.topup_amount},
						beforeSend: function() {
							_app_.submitting = true;
						},
						success: function(data) {
							if (data.status == 200) {
								cl_redirect(data.url);
							}

							else if(data.status == 500) {
								_app_.submitting = false;
								cl_bs_notify(data.message, 5000, "danger");
							}

							else {
								_app_.submitting = false;
								SMColibri.errorMSG();
							}
						}
					});
				}
			}
		});
	});
</script>