<div class="cp-app-container" data-app="changelogs">
    <div class="current-page-name">
        <div class="lp">
            <h2>
                Changelogs
            </h2>
            <ol class="breadcrumb">
                <li>
                    <a href="<?php echo cl_link('admin_panel'); ?>">
                        Control panel
                    </a>
                </li>
                <li class="active">
                    <a href="javascript:void(0);">
                        Changelogs
                    </a>
                </li> 
            </ol>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.2.4 (<time>29 July 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] Previous minor bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.2.3 (<time>24 July 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Added] Cookies alert</p>
                    <p>- [Fixed] Removed sidebar movement when scrolling</p>
                    <p>- [Fixed] Previous minor bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.2.2 (<time>06 July 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] Previous minor bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.2.1 (<time>28 June 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Added] Amazon S3 storage (Admin panel)</p>
                    <p>- [Added] Media upload limit (Admin panel)</p>
                    <p>- [Added] Ability to add multiple admins (Admin panel)</p>
                    <p>- [Added] Header top fix on page scroll</p>
                    <p>- [Added] E-mail verification system</p>
                    <p>- [Added] Username hover popoever</p>
                    <p>- [Added] Voice recorder in the posts section</p>
                    <p>- [Added] Auto detect user language (Guest page)</p>
                    <p>- [Added] API endpoints</p>
                    <p>- [Added] Many improvements in the core of the system</p>
                    <p>- [Fixed] Previous minor bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.2.0 (<time>23 May 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] Previous minor bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.1.9 (<time>22 May 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] Previous minor bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.1.8 (<time>21 May 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] Previous minor bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.1.7 (<time>20 May 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Improved] Emoji system</p>
                    <p>- [Improved] Design</p>
                    <p>- [Added] Mention of autocomplete</p>
                    <p>- [Added] Hashtags of autocomplete</p>
                    <p>- [Updated] Admin panel (Added page update interverl settings)</p>
                    <p>- [Fixed] Previous minor bugs</p>
                    <p>- And more minor improvements in the system</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.1.6 (<time>02 May 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Updated] API</p>
                    <p>- [Fixed] Previous minor bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.1.5 (<time>29 March 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Updated] API</p>
                    <p>- [Fixed] Previous minor bugs</p>
                    <p>- And more minor improvements in the system</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.1.4 (<time>02 March 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Added] Approval system for user ads</p>
                    <p>- [Updated] Script docs</p>
                    <p>- [Updated] API</p>
                    <p>- [Fixed] Previous minor bugs</p>
                    <p>- And more minor improvements in the system</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.1.3 (<time>24 Feb 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Added] Google Ads System for Admin</p>
                    <p>- [Updated] API</p>
                    <p>- [Added] oAuth login disable/enable system</p>
                    <p>- [Added] New welcome page</p>
                    <p>- [Added] Registration start up system</p>
                    <p>- [Added] Publication reporting system</p>
                    <p>- [Added] Live homepage feed updating system</p>
                    <p>- [Added] Post soft hidding system</p>
                    <p>- [Fixed] Follower counting errors after blocking</p>
                    <p>- [Fixed] Thumbnail error for short videos</p>
                    <p>- [Fixed] Bug with Timezone</p>
                    <p>- [Added] Ability to view avatar and profile cover in lightbox</p>
                    <p>- [Added] And also many other improvements in the admin panel and in the core of the script</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.1.2 (<time>07 Feb 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] Bugs with image orientation uploaded from the camera</p>
                    <p>- [Fixed] Bugs with uploading files and freezing the upload slider</p>
                    <p>- [Fixed] Shortcomings with dark theme on mobile and web devices</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.1.1 (<time>03 Feb 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Added] The ability to switch UI themes from admin panel (if any)</p>
                    <p>- [Added] The ability to play Vimeo videos without leaving the page</p>
                    <p>- [Added] Google Maps URL lightbox preview (embed in iFrame)</p>
                    <p>- [Improved] Links (URLs) preview system</p>
                    <p>- [Fixed] Bugs dark theme on login page</p>
                    <p>- [Improved] Some more kernel improvements to stabilize the system</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.9 (<time>22 Jan 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Added] The ability to play YouTube videos without leaving the page</p>
                    <p>- [Added] Ability to edit language texts, without losing changes when updating</p>
                    <p>- [Updated] Script documentation</p>
                    <p>- [Fixed] Bugs with user blocking</p>
                    <p>- [Fixed] Bugs dark theme</p>
                    <p>- [Fixed] Bugs with user removal system</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.8 (<time>05 Jan 2021</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Added] Controlling the length of post characters from the admin panel (600 / or arbitrary)</p>
                    <p>- [Added] System of notification settings</p>
                    <p>- [Added] API endpoints</p>
                    <p>- [Enabled] Login with username</p>
                    <p>- [Added] Dark / light theme mode</p>
                    <p>- [Added] Profile privacy (Who can see profile)</p>
                    <p>- [Improved] Post OG data system</p>
                    <p>- [Added] Post privacy (Who can reply)</p>
                    <p>- [Added] Polls system</p>
                    <p>- [Added] Video lightbox system</p>
                    <p>- [Added] Swifts system (User stories system)</p>
                    <p>- [Added] Admin ads management system</p>
                    <p>- [Added] Ad page view system (For admin)</p>
                    <p>- [Added] Follow privacy system (Who can follow me)</p>
                    <p>- [Added] GDRP system (Import my information)</p>
                    <p>- [Improved] Pages loading speed</p>
                    <p>- [Improved] Improved interface design</p>
                    <p>- [Fixed] Previous bugs</p>
                    <p>- And many more improvements in the core of the script and improved system quality</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.7 (<time>08 October 2020</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] Emergency updates due to previous bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.6 (<time>20 September 2020</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Added] SPA loading system (No hard refreshes anyomore)</p>
                    <p>- [Added] Ads system</p>
                    <p>- [Added] Affiliate system</p>
                    <p>- [Added] User wallet system</p>
                    <p>- [Added] User reporting system</p>
                    <p>- [Added] User block/unblock system</p>
                    <p>- [Added] Link OG data fetching system</p>
                    <p>- [Added] Media uploading progress bar system</p>
                    <p>- [Added] Emoji support to the chat system (Only for desktop browsers)</p>
                    <p>- [Improved] Post-media preloaders</p>
                    <p>- [Improved] Post #htags displaying system</p>
                    <p>- [Improved] User follow suggestion system</p>
                    <p>- [Fixed] Issue with domains (www)</p>
                    <p>- [Fixed] Issue with links to post on social media (Facebook, etc.)</p>
                    <p>- [Fixed] Other minor issues with the script</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.5 (<time>15 July 2020</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Added] User verification system</p>
                    <p>- [Added] Registration confirmation system</p>
                    <p>- [Added] User ban by admin system</p>
                    <p>- [Added] User privacy system</p>
                    <p>- [Added] Welcome page for guests</p>
                    <p>- [Added] Media files (Images, Videos) lazy loading system</p>
                    <p>- [Added] Sitemap creation system</p>
                    <p>- [Fixed] Previous several minor bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.4 (<time>29 June 2020</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] Previous several minor bugs (URLs in posts, image extentions support, etc..)</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.3 (<time>15 June 2020</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- [Feature] function for changing the username specified during registration</p>
                    <p>- [Fixed] bug with drop-down menu on profile settings page</p>
                    <p>- [Fixed] bug with pop-up message on the home page</p>
                    <p>- [Fixed] bug with function of display language for the user</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.2 (<time>11 June 2020</time>) [Emergency update for bug fixes]
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] bug with user gender difference (His/Her) In timeline</p>
                    <p>- [Fixed] bug with dropdown menu For mobile devices</p>
                    <p>- [Fixed] bug moving cover on user profile page</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.1 (<time>30 May 2020</time>) [Emergency update for bug fixes]
                    </h2>
                </div>
                <div class="body">
                    <p>- [Fixed] Previous several important bugs</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        v1.0.0 (<time>21 May 2020</time>)
                    </h2>
                </div>
                <div class="body">
                    <p>- Version 1.0.0 released on 21 May 2020.</p>
                </div>
            </div>
        </div>
    </div>
</div>
